### ISSUE TITLE
Decide what to put on slider

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/odb#10]
- [x] most recent request? 
- [x] link to open data explainer
- [x] link to annoucement
- [x] link to oab

**Comment by JosephMcArthur** [comment]
@markmacgillivray is the first one possible? or most popular?
@markmacgillivray we can also have the map here yes. That's two!

**Comment by JosephMcArthur** [comment]
@markmacgillivray can you clarify what the correct image size or ratio is for this? Is there one, how do you suggest desiging images so that they work at different sizes.

**Comment by JosephMcArthur** [comment]
@chealsye this links in with our email discussion.

**Comment by JosephMcArthur** [comment]
Notes from chat with @chealsye . 
- An open access button logo with text under a header saying "Paywalls got you down?"
- David Himmelstein slide
- slider the announcement. Rocket image, with text overlay with open data button launch. 
- FOR OAB. Rocket image, text overlay mention open data button launch. 
- For OAB. Story slider.

**Comment by chealsye** [comment]
Uploaded Himmelstein quote, OAB story slider, and Paywalls got you down? 
Sizes 800x500 and 800x400
https://github.com/OAButton/backend/commit/abb94068a16df5f3c9929421f5347ed660045376

**Comment by chealsye** [comment]
Uploaded rocket slides. Orange one for the OAB site, more blue one for ODB. I think this will look best. OAB and ODB are noted in file names. Both 800x500 and 800x400 sizes. 
@JosephMcArthur let me know if you want something different, whether totally or just text changes or if you want to add text to indicate someone should click on the image. https://github.com/OAButton/backend/commit/ebfcb0d4a036bf9409962c6de2c7a28efcc83dcb

**Comment by JosephMcArthur** [comment]
We've decided, making another issue for putting them up.
