### ISSUE TITLE
Restyle in ODB Colors

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/odb#2]

**Comment by mtb-za** [comment]
Do we have particular colours yet? Or are these the same as the OAB?

Looking for hex-codes or something similar for theming.

**Comment by JosephMcArthur** [comment]
Emailed!

On 8 February 2016 at 10:23, Martin Bentley <notifications@github.com>
wrote:

> Do we have particular colours yet? Or are these the same as the OAB?
>
> Looking for hex-codes or something similar for theming.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/OAButton/odb/issues/2#issuecomment-181295303>.
>



-- 
Joseph McArthur
Assistant Director: Right to Research Coalition
<http://righttoresearch.org/>
Co-Lead/Founder: Open Access Button <http://openaccessbutton.org/>
Twitter: @Mcarthur_Joe <https://twitter.com/Mcarthur_Joe>
Skype: joseph_mcarthur
Linkedin <http://linkd.in/1BgZ1jU>

**Comment by mtb-za** [comment]
Colours seem to be the same.

For reference:
oabutton dark blue (which is the main text colour) is 212f3f
medium blue is 29cae6
light blue is 9dfdfd
orange (the action colour) is f04717
grey is c8c8c8
white is ffffff

**Comment by mtb-za** [comment]
Missed that there was an additional colour listed:

5E8EC1 which is a medium-dark blue.

**Comment by mtb-za** [comment]
Main colour changed from 212f3f to 5e8ec1 in oabutton.css: https://github.com/OAButton/odb/commit/ba74052a25975da5fd2b147c065b0268828ea33b

**Comment by mtb-za** [comment]
So the colour needs to be #398bc5

Will fix it now.

**Comment by mtb-za** [comment]
A note to anyone editing the pages:

The new blue does *not* work on the orange, for example in button elements.

**Comment by JosephMcArthur** [comment]
But we're going to use white yes?

On Thursday, 18 February 2016, Martin Bentley <notifications@github.com>
wrote:

> A note to anyone editing the pages:
>
> The new blue does *not* work on the orange, for example in button
> elements.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/OAButton/odb/issues/2#issuecomment-185716311>.
>


-- 
Joseph McArthur
Assistant Director: Right to Research Coalition
<http://righttoresearch.org/>
Co-Lead/Founder: Open Access Button <http://openaccessbutton.org/>
Twitter: @Mcarthur_Joe <https://twitter.com/Mcarthur_Joe>
Skype: joseph_mcarthur
Linkedin <http://linkd.in/1BgZ1jU>
