### ISSUE TITLE
To begin, make first email for new request to require admin approval

### ISSUE THREAD

**Issue by markmacgillivray** [OAButton/odb#20]
A new request should start the email the author chain, but that chain should FIRST go to a list where the ODB admin can approve or deny the send of the first email. Ideally the ODB admin should be able to edit the email and send or not send.

Put a header up on the requests page to say they are being moderated before sending, so people know they are not yet instant.

**Comment by JosephMcArthur** [comment]
I think all we need here is "Put a header up on the requests page to say they are being moderated before sending, so people know they are not yet instant."

**Comment by markmacgillivray** [comment]
Done, they say awaiting moderation
