### ISSUE TITLE
Servers

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/odb#40]
Is the system on production servers? Seems to show "loading" between pages. Worried this might cause an issue if we get a boat load of traffic on Monday.

**Comment by markmacgillivray** [comment]
Yeah it's OK, that's just something meteor does on first page load, it
doesn't mean it's having trouble. But once we move the static pages off to
a separate repo, you won't even see that until you go to the login or
account pages. It's only running on one server though, so if we get big
load we'll have to start up another.
