### ISSUE TITLE
API key not generated

### ISSUE THREAD

**Issue by wetneb** [OAButton/odb#51]
Hi,

No API key is generated when I do the following steps:
- sign in with my email address
- click on the confirmation link in the email I get
- tick the three boxes (they do not disappear)
The API key field is still blank, so I can't use the button :-(

**Comment by markmacgillivray** [comment]
Which email address are you using when you see this problem?

**Comment by wetneb** [comment]
my_github_username at gmail.com

**Comment by markmacgillivray** [comment]
How odd. I can see your account, it looks fine, has an API key, is logged in, shows as online, last activity just four minutes ago, it has recorded your username and that you ticked the boxes and set your profession... can you try pressing the logout button on the account page, then try the login again?

**Comment by markmacgillivray** [comment]
There was possible issues earlier, about five hours ago, when I was updating the live site to run static pages for some sections, and I had trouble getting the cookies to reset properly. But that appears to be fine now, and has not caused any issues since then, as far as I can tell.

**Comment by markmacgillivray** [comment]
But your account had not even been created then, so it can't be that...

**Comment by markmacgillivray** [comment]
Ah but there are other accounts that look like they may have been created by you, earlier in the day - maybe an errant cookie is causing issues? If so try hitting the logout button, then go to https://openaccessbutton.org/login manually by typing it into the URL bar, then try logging in.

**Comment by markmacgillivray** [comment]
sorry wrong link - https://opendatabutton.org/login

**Comment by markmacgillivray** [comment]
Server logs show a successful login by you just now, did it work?

**Comment by wetneb** [comment]
![bug](http://pintoch.ulminfo.fr/f15c2a8a6e/bug.png)

**Comment by markmacgillivray** [comment]
Hmmmmmm. I don't know. All looks like it should on the server side, but your snapshot above clearly indicates it is not right for you. Your account does exist, I will email you your API key, then try out the button and let us know if it works for you anyway. I don't know what else to try just now to fix the website account page for you, and I am busy with other things tonight so will have to leave it until tomorrow. I will email to the address you registered that account with. Thanks for letting us know of the issue!

**Comment by markmacgillivray** [comment]
Actually I think I have found the fix. Please check again now - I emailed your key to you, but you should now see it on the account page too.

**Comment by wetneb** [comment]
It's fixed indeed.

**Comment by markmacgillivray** [comment]
Excellent :)
