### ISSUE TITLE
Adding a DOI field in requests

### ISSUE THREAD

**Issue by dhimmel** [OAButton/odb#58]
Having each request linked to a URL and not a DOI seems like it will be susceptible to linkrot. Additionally, it's much easier to get metadata for a DOI. Also searching for requests by DOI makes more sense than search by URL, since there are many URLs for a single article.

I get that it would be undesirable to only support pages with DOIs, so allowing an optional field may be the way to go.

**Comment by dhimmel** [comment]
As an example aesthetic benefit, [account pages](https://opendatabutton.org/account) would display:

```
Supporting data for DOI: 10.1007/s11192-015-1592-8
```

rather than

```
Supporting data for the article at http://link.springer.com/article/10.1007/s11192-015-1592-8/fulltext.html
```

**Comment by JosephMcArthur** [comment]
Thanks @dhimmel! 

@markmacgillivray any thoughts on this? I know many things don't have URL's, so this doesn't work in all places but seems like it would be good where possible.

**Comment by JosephMcArthur** [comment]
Issue moved to [OAButton/backend #169](https://github.com/OAButton/backend/issues/169) via [**ZenHub**](https://www.zenhub.com/)
