### ISSUE TITLE
Requests created on button open rather than submission

### ISSUE THREAD

**Issue by dhimmel** [OAButton/odb#59]
I believe requests are being created prior to pressing submit. The result is that I have multiple open data requests for the same piece of content in https://opendatabutton.org/account:

![multiple open data button requests](https://cloud.githubusercontent.com/assets/1117703/14406319/62df5600-fe59-11e5-9716-4f504a2b14e8.png)

Not sure exactly how this happened, but I do not I've only submitted requests twice and hence there should only be two requests.

**Comment by JosephMcArthur** [comment]
This issue was moved to OAButton/backend#150
