### ISSUE TITLE
Replace filler text

### ISSUE THREAD

**Issue by mtb-za** [OAButton/odb#6]

**Comment by mtb-za** [comment]
Following on from #5.

**Comment by mtb-za** [comment]
Hey @JosephMcArthur, who should I ask for the copy here? Are you doing it or Chealsye?

**Comment by JosephMcArthur** [comment]
Bit of both I imagine.
https://docs.google.com/document/d/1RYtIa3mJGJHD4PsEyMSCMGvNQksg-j42L-D8R8sNrq4/edit#

On 23 February 2016 at 08:57, Martin Bentley <notifications@github.com>
wrote:

> Hey @JosephMcArthur <https://github.com/JosephMcArthur>, who should I ask
> for the copy here? Are you doing it or Chealsye?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/OAButton/odb/issues/6#issuecomment-187606812>.
>



-- 
Joseph McArthur
Assistant Director: Right to Research Coalition
<http://righttoresearch.org/>
Co-Lead/Founder: Open Access Button <http://openaccessbutton.org/>
Twitter: @Mcarthur_Joe <https://twitter.com/Mcarthur_Joe>
Skype: joseph_mcarthur
Linkedin <http://linkd.in/1BgZ1jU>

**Comment by JosephMcArthur** [comment]
Okay first, new link: https://docs.google.com/document/d/1Dwdln9Cs83at8iBRksn_d-8aSkJRzsCUS1s2GbbRTPc/edit#heading=h.r9u69pefy8lt

Second. Lets get rid of support on this site.
