### ISSUE TITLE
[UI convention] Tick exclusive choice with several choice tick

### ISSUE THREAD

**Issue by jibe-b** [OAButton/odb#62]
Please forgive the approximative vocabulary I might use.

When entering a new request on https://openaccessbutton.org/request/new then entering a DOI
the next step is to tick either the request for
[ ] article
[ ] data
and the tick boxes _behave_ like unique-choice boxes, though _looking like_ multiple-choice boxes.

![tick-boxes](https://cloud.githubusercontent.com/assets/6146483/22591292/14fdbd30-ea14-11e6-878a-6d02ff4b4ef3.png) should look like ![single-choice-tick-box](https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcTrFyRwzJPBuTuSm1HTb9fUlpH7IoZDa737FVN9V8qwfp4_vPDXtA)

**Comment by JosephMcArthur** [comment]
Thanks @jibe-b, this is a good point! I'm going to move this to the repo we actively use for issues /OAButton/discussion

**Comment by JosephMcArthur** [comment]
Issue moved to [OAButton/discussion #512](https://github.com/OAButton/discussion/issues/512) via [**ZenHub**](https://www.zenhub.com/)
