### ISSUE TITLE
Propose to author to add all her/his papers to an open archive

### ISSUE THREAD

**Issue by jibe-b** [OAButton/odb#63]
When an author receives an email asking to release a specific paper, s.he may be willing to release all his/her papers at a time.

Hence, I suggest to add a link to dissem.in in the standard email, suggesting to add the papers missing in open archives (possibly http://dissem.in/search/?authors=<author>).

dissem.in is still under development, as is OAB.

**Comment by jibe-b** [comment]
cc @a3nm

**Comment by a3nm** [comment]
Yeah, I think this is a good idea! :)

**Comment by JosephMcArthur** [comment]
Thanks for the suggestion, we like the idea too! This is already being discussed in https://github.com/OAButton/discussion/issues/747 :)
