### ISSUE TITLE
Move domain

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/odb#8]
This will allow chrome plug in to work, and new website changes for OSF work to go live. 

- [ ] Install SSL certificate (I've brought this)
- [ ] point API's at the right place. api.opendatabutton.rog
- [ ] Point domain at new servers

**Comment by markmacgillivray** [comment]
pls point opendatabutton.org and all subdomains to 178.62.93.81

**Comment by markmacgillivray** [comment]
And also point osf.openaccessbutton.org there too - but NOT the rest of openaccessbutton.org, which needs to remain pointing at the old system until ff can be released (mid april)

**Comment by JosephMcArthur** [comment]
Tagging @davidecarroll in this, since he controls the domain :)

**Comment by davidecarroll** [comment]
this is done
